### ISSUE TITLE
代理使用

### ISSUE THREAD

**Issue by flaymes** [lizongying/go-crawler#22]
您好，代理的配置和使用能否出一个较为详细的说明呢？

**Comment by lizongying** [comment]
在配置中設置代理：
```
proxy_list:
  - name:
    uri: http://127.0.0.1:8888
proxy: // name
```

啟用代理：
SetProxyEnable(true)

```
	s.NewRequest(ctx).
		SetUrl(response.Url()).
		SetProxyEnable(true).
		SetExtra(&ExtraOk{
			Count: count + 1,
		}).
		SetCallBack(s.ParseOk).
		UnsafeYield()
```

如果`enable_proxy_middleware: true`，默認，會隨機proxy_list；
如果false，會使用name為proxy字段的代理

也可以在請求中設置具體代理地址：
SetProxy()
